MODEL:
  ARCHITECTURE: DepthVGGorAlex

IMG_NET:
  LOSS: MultiplePredictionLoss
  N_LABELS: 1000

DATASET:
  CLASS: ImageDataset
  NAME: coco
  VERSION: boulder
  DATA_ROOT: datasets/coco/annotations/
  IMG_ROOT: datasets/coco/images/train2014/
  DEPTH_ROOT: datasets/coco/images/megadepth/

IMG_PROCESSING:
  USE_DEPTH: True

OUTPUT:
  CHECKPOINT_PREFIX: depth_image_classifier

TRAINING:
  N_EPOCH: 100
  DROPOUT: 0.5