MODEL:
  ARCHITECTURE: MaoEtAl_baseline

DATASET:
  NAME: refcocog
  VERSION: google
  DATA_ROOT: datasets/coco/refcocog
  IMG_ROOT: datasets/coco/images/train2014/

IMG_PROCESSING:
  USE_DEPTH: False

OUTPUT:
  CHECKPOINT_PREFIX: maoetal_baseline_batch64_hidden1024_feats2005_dropout0.0_l21.0e-05.mdl

