MODEL:
  ARCHITECTURE: MaoEtAl_depth

IMG_NET:
  N_LABELS: 80
  USE_CUSTOM: True
  CUSTOM: models/mscoco_depth_classification_l2_10e-5_BCE.mdl.checkpoint65
  FEATS: 165

DATASET:
  NAME: sunspot
  VERSION: boulder
  DATA_ROOT: datasets/sunspot/annotations/
  IMG_ROOT: datasets/sunspot/images/
  DEPTH_ROOT: datasets/sunspot/images/

IMG_PROCESSING:
  USE_DEPTH: True

TRAINING:
  BATCH_SIZE: 8
  LEARNING_RATE: 0.0001

TEST:
  DO_TEST: True

OUTPUT:
  CHECKPOINT_PREFIX: refcocog_depth_baseline_ckpt_65

