MODEL:
  ARCHITECTURE: DepthVGGorAlex

IMG_NET:
  N_LABELS: 38
  USE_CUSTOM: True
  CUSTOM: models/mscoco_depth_classification_lr_10e-5_l2_1e-3_BCE.mdl
  FEATS: 81

DATASET:
  CLASS: ImageDataset
  NAME: sunrgbd
  VERSION: boulder
  DATA_ROOT: datasets/SUNRGBD/annotations/
  IMG_ROOT: datasets/SUNRGBD/images/
  DEPTH_ROOT: datasets/SUNRGBD/images/

IMG_PROCESSING:
  USE_DEPTH: True

OUTPUT:
  CHECKPOINT_PREFIX: sunspot_transfer_depth_classification

TRAINING:
  L2_FRACTION: 1e-3
  LEARNING_RATE: 1e-5
  N_EPOCH: 100
  DROPOUT: 0.5