MODEL:
  ARCHITECTURE: MaoEtAl_baseline
  USE_PRETRAINED: True
    PRETRAINED: models/refcocog_baseline_custom_vgg.mdl

IMG_NET:
  N_LABELS: 80
  USE_CUSTOM: True
  CUSTOM: models/mscoco_classification_l2_10e-5_BCE.mdl.checkpoint35
  FEATS: 165

DATASET:
  NAME: sunspot
  VERSION: boulder
  DATA_ROOT: datasets/sunspot/annotations/
  IMG_ROOT: datasets/sunspot/images/

IMG_PROCESSING:
  USE_DEPTH: False

OUTPUT:
  CHECKPOINT_PREFIX: sunspot_baseline_custom_vgg
